apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: helm-deployment
data:
  alertmanager.yml: |
    route:
      receiver: 'sns-alerts'
      group_by: ['alertname', 'namespace', 'pod']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
    - name: 'sns-alerts'
      sns_configs:
      - api_url: "https://sns.us-east-1.amazonaws.com/"
        sigv4:
          region: us-east-1
        topic_arn: "arn:aws:sns:us-east-1:<YOUR_ACCOUNT_ID>:k8s-alerts"
        subject: "HighPodRestart Alert"
