apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: otel-demo
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: "2.0.2"
    app.kubernetes.io/part-of: opentelemetry-demo
data:
  dummy.json: |
    {
      "title": "Placeholder Dashboard",
      "panels": [],
      "timezone": "browser",
      "schemaVersion": 16,
      "version": 0
    }
